//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuhui.OH.Mvc.TrainTimeWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="TrainTimeWebService.TrainTimeWebServiceSoap")]
    public interface TrainTimeWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationNameDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStationNameDataSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getStationAndTimeByTrainCode(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getVersionTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getVersionTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeDataSetByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStationAndTimeDataSetByTrainCode(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeDataSetByLikeTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStationAndTimeDataSetByLikeTrainCode(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDetailInfoByTrainCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getDetailInfoByTrainCode(string TrainCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getStationName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStationAndTimeByStationName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStationAndTimeByStationName(string StartStation, string ArriveStation, string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrainTimeWebServiceSoapChannel : Tuhui.OH.Mvc.TrainTimeWebService.TrainTimeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainTimeWebServiceSoapClient : System.ServiceModel.ClientBase<Tuhui.OH.Mvc.TrainTimeWebService.TrainTimeWebServiceSoap>, Tuhui.OH.Mvc.TrainTimeWebService.TrainTimeWebServiceSoap {
        
        public TrainTimeWebServiceSoapClient() {
        }
        
        public TrainTimeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainTimeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainTimeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainTimeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getStationNameDataSet() {
            return base.Channel.getStationNameDataSet();
        }
        
        public string[] getStationAndTimeByTrainCode(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeByTrainCode(TrainCode, UserID);
        }
        
        public string getVersionTime() {
            return base.Channel.getVersionTime();
        }
        
        public System.Data.DataSet getStationAndTimeDataSetByTrainCode(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeDataSetByTrainCode(TrainCode, UserID);
        }
        
        public System.Data.DataSet getStationAndTimeDataSetByLikeTrainCode(string TrainCode, string UserID) {
            return base.Channel.getStationAndTimeDataSetByLikeTrainCode(TrainCode, UserID);
        }
        
        public System.Data.DataSet getDetailInfoByTrainCode(string TrainCode, string UserID) {
            return base.Channel.getDetailInfoByTrainCode(TrainCode, UserID);
        }
        
        public string[] getStationName() {
            return base.Channel.getStationName();
        }
        
        public System.Data.DataSet getStationAndTimeByStationName(string StartStation, string ArriveStation, string UserID) {
            return base.Channel.getStationAndTimeByStationName(StartStation, ArriveStation, UserID);
        }
    }
}
